# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Accengage specs source repo
source 'https://github.com/Accengage/ios-pod-specs.git'
 
# CocoaPods master specs repo
source 'https://github.com/CocoaPods/Specs.git'

target 'AccengageProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  use_frameworks!


  # Pods for AccengageProject
  pod 'Accengage-iOS-SDK', '~> 6.1'

  target 'AccengageProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AccengageProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AccengageProject-tvOS

  target 'AccengageProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
